/* tslint:disable */
/* eslint-disable */
/**
 * Poker Player API
 * Poker Player API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The player's bet.
 * @export
 * @interface Bet
 */
export interface Bet {
    /**
     * 
     * @type {number}
     * @memberof Bet
     */
    bet?: number;
}
