/* tslint:disable */
/* eslint-disable */
/**
 * Poker Player API
 * Poker Player API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The suit of a card.
 * @export
 * @enum {string}
 */
export enum Suit {
    HEARTS = 'HEARTS',
    SPADES = 'SPADES',
    CLUBS = 'CLUBS',
    DIAMONDS = 'DIAMONDS'
}

