/* tslint:disable */
/* eslint-disable */
/**
 * Poker Player API
 * Poker Player API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Card } from './card';
import { Player } from './player';
/**
 * The poker table, representing the current game state.
 * @export
 * @interface Table
 */
export interface Table {
    /**
     * The list of community cards on the table, visible to everyone.
     * @type {Array<Card>}
     * @memberof Table
     */
    communityCards: Array<Card>;
    /**
     * The list of players at the table, including you.
     * @type {Array<Player>}
     * @memberof Table
     */
    players: Array<Player>;
    /**
     * The number of the current round.
     * @type {number}
     * @memberof Table
     */
    round: number;
    /**
     * The current small blind of this round.
     * @type {number}
     * @memberof Table
     */
    smallBlind: number;
    /**
     * The minimum amount of chips you have to bet if you want to keep playing.
     * @type {number}
     * @memberof Table
     */
    minimumBet: number;
    /**
     * The minimum amount of chips you have to bet if you want to raise.
     * @type {number}
     * @memberof Table
     */
    minimumRaise: number;
    /**
     * The current size of the pot of this round.
     * @type {number}
     * @memberof Table
     */
    pot: number;
    /**
     * The index of the player whose turn it is. It's you!
     * @type {number}
     * @memberof Table
     */
    activePlayer: number;
    /**
     * The index of the player who is the dealer of this round.
     * @type {number}
     * @memberof Table
     */
    currentDealer: number;
}
